// 食物分类预设
export const FOOD_CATEGORIES = [
  {
    name: "主食",
    items: [
      { name: "米饭", emoji: "🍚" },
      { name: "面条", emoji: "🍜" },
      { name: "面包", emoji: "🥐" },
      { name: "饺子", emoji: "🥟" },
      { name: "包子", emoji: "🫓" },
      { name: "粥", emoji: "🥣" },
      { name: "炒饭", emoji: "🍛" },
      { name: "汉堡", emoji: "🍔" },
      { name: "意面", emoji: "🍝" },
      { name: "披萨", emoji: "🍕" },
      { name: "寿司", emoji: "🍣" },
      { name: "煎饼", emoji: "" },
      { name: "馄饨", emoji: "" },
      { name: "馒头", emoji: "" },
      { name: "安素", emoji: "" },
      { name: "能全力", emoji: "" },
      { name: "瑞能", emoji: "" },
      { name: "瑞代", emoji: "" },
      { name: "百普力", emoji: "" },
    ],
  },
  {
    name: "肉蛋奶",
    items: [
      { name: "鸡蛋", emoji: "🥚" },
      { name: "煎蛋", emoji: "🍳" },
      { name: "牛奶", emoji: "🥛" },
      { name: "酸奶", emoji: "🫗" },
      { name: "豆浆", emoji: "🥛" },
      { name: "豆腐", emoji: "" },
      { name: "鸡肉", emoji: "🍗" },
      { name: "鸭肉", emoji: "🦆" },
      { name: "猪肉", emoji: "🐷" },
      { name: "牛肉", emoji: "🐮" },
      { name: "羊肉", emoji: "🐑" },
      { name: "排骨", emoji: "🍖" },
      { name: "培根", emoji: "🥓" },
      { name: "鱼", emoji: "🐟" },
      { name: "虾", emoji: "🦐" },
      { name: "螃蟹", emoji: "🦀" },
      { name: "龙虾", emoji: "🦞" },
    ],
  },
  {
    name: "果蔬",
    items: [
      // 蔬菜
      { name: "青菜", emoji: "🥬" },
      { name: "白菜", emoji: "🥬" },
      { name: "土豆", emoji: "🥔" },
      { name: "玉米", emoji: "🌽" },
      { name: "西红柿", emoji: "🍅" },
      { name: "黄瓜", emoji: "🥒" },
      { name: "胡萝卜", emoji: "🥕" },
      { name: "西兰花", emoji: "🥦" },
      { name: "蘑菇", emoji: "🍄" },
      { name: "南瓜", emoji: "🎃" },
      { name: "茄子", emoji: "🍆" },
      // 水果
      { name: "苹果", emoji: "🍎" },
      { name: "香蕉", emoji: "🍌" },
      { name: "橙子", emoji: "🍊" },
      { name: "西瓜", emoji: "🍉" },
      { name: "葡萄", emoji: "🍇" },
      { name: "草莓", emoji: "🍓" },
      { name: "桃子", emoji: "🍑" },
      { name: "梨", emoji: "🍐" },
      { name: "芒果", emoji: "🥭" },
      { name: "猕猴桃", emoji: "🥝" },
      { name: "樱桃", emoji: "🍒" },
    ],
  },
  {
    name: "零食饮料",
    items: [
      { name: "饼干", emoji: "🍪" },
      { name: "坚果", emoji: "🥜" },
      { name: "薯片", emoji: "🥔" },
      { name: "果干", emoji: "🍇" },
      { name: "巧克力", emoji: "🍫" },
      { name: "蛋糕", emoji: "🍰" },
      { name: "冰淇淋", emoji: "🍦" },
      { name: "咖啡", emoji: "☕" },
      { name: "茶", emoji: "🍵" },
      { name: "果汁", emoji: "🧃" },
      { name: "可乐", emoji: "🥤" },
      { name: "奶茶", emoji: "🧋" },
      { name: "啤酒", emoji: "🍺" },
      { name: "白酒", emoji: "🍶" },
      { name: "红酒", emoji: "🍷" },
    ],
  },
] as const;

// 进食量选项
export const AMOUNT_OPTIONS = [
  { value: 0, label: "少量" },
  { value: 1, label: "较少" },
  { value: 2, label: "适中" },
  { value: 3, label: "较多" },
  { value: 4, label: "大量" },
] as const;
